
text_extensions: [ 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'ms', 'mustache', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]

output_dir: output

index_filenames: [ 'index.html' ]

enable_output_diff: false

prune:
  auto_prune: false
  exclude: [ '.git', '.hg', '.svn', 'CVS' ]

data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
    allow_periods_in_identifiers: false
  -
    type: static
    items_root: /static

watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true

